[mgr]
ratio=[2, 3, 3]
sort_by="alphabetical"
sort_dir_first=true
linemode="size"
show_hidden=true

[preview]
tab_size=3

[opener]
neovim = [
    { run = "nvim %s",  desc = "Neovim", block = true, for = "unix" },
]
pdf_web = [
    { run = "brave %s", desc = "Browser", block = false, orphan = true, for = "unix" },
]
pdf_app = [
    { run = "evince %s", desc = "Evince", block = false, orphan = true, for = "unix" },
]
img_web = [
    { run = "gimp %s", desc = "Gimp", block = false, orphan = true, for = "unix" },
]
img_app = [
    { run = "brave %s", desc = "Browser", block = false, orphan = true, for = "unix" },
]

[open]
rules = [
    { mime = "text*", use = "neovim" },
    { mime = "*wine*", use = "neovim" },
    { mime = "*pdf", use = ["pdf_web", "pdf_app"] },
    { mime = "image*", use = ["img_web", "img_app"] },
]
