[mgr]
ratio=[2, 3, 3]
sort_by="alphabetical"
sort_dir_first=true
linemode="size"
show_hidden=true

[preview]
tab_size=3

[opener]
libreoffice = [
    { run = "libreoffice %s1", desc = "Libreoffice", orphan = true, for = "unix" }
]
run = [
    { run = "%s1", desc= "Execute", block = true },
]
neovim = [
    { run = "nvim %s",  desc = "Neovim", block = true },
]
web = [
    { run = "brave %s", desc = "Browser", orphan = true, for = "unix" },
]
pdf_app = [
    { run = "evince %s", desc = "Evince", orphan = true, for = "unix" },
]
img_app = [
    { run = "gimp %s", desc = "Gimp", orphan = true, for = "unix" },
]
windows_open = [
    { run = 'explorer "%s1"', orphan = true, desc = "Open", for = "windows" },
]

decompress = [
    { run = "7z x %s1", block = true, desc = "Decompress" },
]

[open]
rules = [
    { mime = "*msword", use = ["windows_open", "libreoffice"] },
    { mime = "*opendocument*", use = ["windows_open", "libreoffice"] },
    { mime = "*officedocument*", use = ["windows_open", "libreoffice"] },
    { mime = "*html", use = ["windows_open", "web", "neovim"] },
    { mime = "text*", use = "neovim" },
    { mime = "inode/empty", use = "neovim" },
    { mime = "*javascript", use = "neovim" },
    { mime = "*wine*", use = "neovim" },
    { mime = "*pdf", use = ["web", "pdf_app", "windows_open"] },
    { mime = "image*", use = ["web", "img_app", "windows_open"] },
    { mime = "*executable*", use = "run" },
    { mime = "*json*", use = "neovim" },
    { mime = "*ms-shortcut", use = "windows_open" },
    { mime = "*zip", use = "decompress" },
    { mime = "*compressed", use = "decompress" },
    { mime = "*rar", use = "decompress" },
    { mime = "*ms-msi", use = "windows_open"}
]

[plugin]
prepend_previewers = [
    { mime = "*executable*",   run = "exiftool" }
]
