[mgr]
ratio=[2, 3, 3]
sort_by="alphabetical"
sort_dir_first=true
linemode="size"
show_hidden=true

[preview]
tab_size=3

[opener]
edit = [
    { run = "nvim %*",  desc = "Neovim", block = true, for = "windows" },
    { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
]
open = [
    { run = "explorer %*", desc = "Explorer", block = true, for = "windows" },
    { run = "xdg-open $@", desc = "Browser", block = true, for = "unix" },
]
term = [
    { run = "%*", desc = "Browser", block = true, for = "windows" },
]

pdf = [
    { run = 'evince "$@" &', desc = "PDF reader", block = true, for = "unix"},
]

[open]
rules = [
    { name = "*.html", use = "term" },
    { name = "*.pdf", use = ["pdf", "open"] },
    { mime = "text/*", use = "edit" },
    { mime = "application/ms-shortcut", use = "open" },
    { mime = "application/*", use = "edit" },
    { mime = "inode/directory", use = "open"},
]
